@startuml

class MainActivity{
 private MyServerSocket serverSocket;
 private ClientSocket clientSocket;
 private WifiDirectBroadcastReciever mBroadcast;
}
class DeviceList
class WifiDirectBroadcastReciever
class LevelsMenu
class StartGameMenu
class Login
class BackgroundTimer
class BattleshipLvl
class ImagePuzzleLvl
class KnowledgeLvl{
    private List<Question> data;
    private Manager manager;
}
class ImagePuzzleHardLvl
class MessageWin
class MessageLoose
class ErrorWifi
class NoDevices
class Question
class Manager{
    private FirebaseHelper helper;
}
class FirebaseHelper
class ClientSocket
class MyServerSocket
class Activity
class Fragment

interface GetMessageListener
interface KnowledgeLvlCallback
interface SocketCallback
interface LevelsMenu.LevelPressedListener
interface NoDevices.RetryInterface
interface DeviceList.DeviceActionListener
interface StartGameMenu.StartMenuListener

MainActivity ..|> GetMessageListener
MainActivity ..|> SocketCallback
MainActivity ..|> NoDevices.RetryInterface
MainActivity ..|> LevelsMenu.LevelPressedListener
MainActivity ..|> DeviceList.DeviceActionListener
MainActivity ..|> StartGameMenu.StartMenuListener

MainActivity <|-- Activity
ErrorWifi <|-- Activity
Login <|--Activity
StartGameMenu<|--Activity

DeviceList<|--Fragment
LevelsMenu<|--Fragment
KnowledgeLvl <|--Fragment
ImagePuzzleLvl <|--Fragment
ImagePuzzleHardLvl <|--Fragment
BattleshipLvl <|--Fragment
MessageWin <|--Fragment
MessageLoose <|--Fragment
NoDevices <|--Fragment

ClientSocket <|--Thread
MyServerSocket <|--Thread
BackgroundTimer <|--Thread

MainActivity -- LevelsMenu
MainActivity -- BattleshipLvl
MainActivity -- ImagePuzzleLvl
MainActivity -- ImagePuzzleHard
MainActivity -- KnowledgeLvl
MainActivity -- NoDevices
MainActivity -- ErrorWifi
MainActivity -- DeviceList
MainActivity -- StartMenuGame






KnowledgeLvl ..|>KnowledgeLvlCallback









@enduml